/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as JwtDebugRouteImport } from './routes/jwt-debug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestaurantsRestaurantIdRouteImport } from './routes/restaurants/$restaurantId'

const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const JwtDebugRoute = JwtDebugRouteImport.update({
  id: '/jwt-debug',
  path: '/jwt-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRestaurantIdRoute = RestaurantsRestaurantIdRouteImport.update({
  id: '/$restaurantId',
  path: '/$restaurantId',
  getParentRoute: () => RestaurantsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jwt-debug': typeof JwtDebugRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/restaurants/$restaurantId': typeof RestaurantsRestaurantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jwt-debug': typeof JwtDebugRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/restaurants/$restaurantId': typeof RestaurantsRestaurantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jwt-debug': typeof JwtDebugRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/restaurants/$restaurantId': typeof RestaurantsRestaurantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/jwt-debug' | '/restaurants' | '/restaurants/$restaurantId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/jwt-debug' | '/restaurants' | '/restaurants/$restaurantId'
  id:
    | '__root__'
    | '/'
    | '/jwt-debug'
    | '/restaurants'
    | '/restaurants/$restaurantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JwtDebugRoute: typeof JwtDebugRoute
  RestaurantsRoute: typeof RestaurantsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jwt-debug': {
      id: '/jwt-debug'
      path: '/jwt-debug'
      fullPath: '/jwt-debug'
      preLoaderRoute: typeof JwtDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$restaurantId': {
      id: '/restaurants/$restaurantId'
      path: '/$restaurantId'
      fullPath: '/restaurants/$restaurantId'
      preLoaderRoute: typeof RestaurantsRestaurantIdRouteImport
      parentRoute: typeof RestaurantsRoute
    }
  }
}

interface RestaurantsRouteChildren {
  RestaurantsRestaurantIdRoute: typeof RestaurantsRestaurantIdRoute
}

const RestaurantsRouteChildren: RestaurantsRouteChildren = {
  RestaurantsRestaurantIdRoute: RestaurantsRestaurantIdRoute,
}

const RestaurantsRouteWithChildren = RestaurantsRoute._addFileChildren(
  RestaurantsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JwtDebugRoute: JwtDebugRoute,
  RestaurantsRoute: RestaurantsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
